import { API_BASE_URL } from './authService'; // Re-use API_BASE_URL

export interface HeroSettings {
  _id?: string; // Optional, as it's generated by MongoDB
  settings_id: string;
  hero_background_image_url?: string;
  hero_personal_photo_url?: string;
  hero_main_title: string;
  hero_subtitle: string;
  hero_bio_content: string;
  hero_button_1_label: string;
  hero_button_2_label: string;
}

export const DEFAULT_HERO_SETTINGS: HeroSettings = {
  settings_id: 'hero_settings',
  hero_personal_photo_url: '/placeholder.jpg',
  hero_main_title: 'Angelo Developer',
  hero_subtitle: 'Creative Developer',
  hero_bio_content: 'Based in Taiwan, creating premium digital experiences with a focus on motion and interaction.',
  hero_button_1_label: 'View Work',
  hero_button_2_label: 'Contact Me',
};

async function getErrorMessage(response: Response, fallback: string): Promise<string> {
  try {
    const errorData = await response.json();
    return errorData.detail || fallback;
  } catch {
    return fallback;
  }
}

export interface SiteSettings {
  _id?: string;
  settings_id: string;
  contact_email: string;
  contact_phone: string;
  contact_location: string;
  social_github: string;
  social_instagram: string;
  social_youtube: string;
  portfolio_title: string;
  portfolio_subtitle: string;
  blog_title: string;
}

/**
 * Fetches the Hero section settings from the backend.
 * @returns A Promise that resolves to HeroSettings.
 */
export async function getHeroSettings(): Promise<HeroSettings> {
  try {
    const response = await fetch(`${API_BASE_URL}/api/settings/hero`, {
      method: 'GET',
      headers: {
        'Content-Type': 'application/json',
      },
    });

    if (!response.ok) {
      throw new Error(await getErrorMessage(response, 'Failed to fetch hero settings'));
    }

    return response.json();
  } catch {
    return DEFAULT_HERO_SETTINGS;
  }
}

/**
 * Updates the Hero section settings in the backend.
 * Requires an admin JWT token for authorization.
 * @param settings - The HeroSettings object to update.
 * @param token - The JWT access token for authentication.
 * @returns A Promise that resolves to the updated HeroSettings.
 */
export async function updateHeroSettings(settings: HeroSettings, token: string): Promise<HeroSettings> {
  const response = await fetch(`${API_BASE_URL}/api/settings/hero`, {
    method: 'PUT',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${token}`,
    },
    body: JSON.stringify(settings),
  });

  if (!response.ok) {
    throw new Error(await getErrorMessage(response, 'Failed to update hero settings'));
  }

  return response.json();
}

export async function getSiteSettings(): Promise<SiteSettings> {
  const response = await fetch(`${API_BASE_URL}/api/settings/site`, {
    method: 'GET',
    headers: {
      'Content-Type': 'application/json',
    },
  });

  if (!response.ok) {
    const errorData = await response.json();
    throw new Error(errorData.detail || 'Failed to fetch site settings');
  }

  return response.json();
}

export async function updateSiteSettings(settings: SiteSettings, token: string): Promise<SiteSettings> {
  const response = await fetch(`${API_BASE_URL}/api/settings/site`, {
    method: 'PUT',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${token}`,
    },
    body: JSON.stringify(settings),
  });

  if (!response.ok) {
    const errorData = await response.json();
    throw new Error(errorData.detail || 'Failed to update site settings');
  }

  return response.json();
}
