import { API_BASE_URL } from './authService'; // Re-use API_BASE_URL

export interface HeroSettings {
  _id?: string; // Optional, as it's generated by MongoDB
  settings_id: string;
  hero_background_image_url?: string;
  hero_personal_photo_url?: string;
  hero_main_title: string;
  hero_subtitle: string;
  hero_bio_content: string;
  hero_button_1_label: string;
  hero_button_2_label: string;
}

/**
 * Fetches the Hero section settings from the backend.
 * @returns A Promise that resolves to HeroSettings.
 */
export async function getHeroSettings(): Promise<HeroSettings> {
  const response = await fetch(`${API_BASE_URL}/api/settings/hero`, {
    method: 'GET',
    headers: {
      'Content-Type': 'application/json',
    },
  });

  if (!response.ok) {
    const errorData = await response.json();
    throw new Error(errorData.detail || 'Failed to fetch hero settings');
  }

  return response.json();
}

/**
 * Updates the Hero section settings in the backend.
 * Requires an admin JWT token for authorization.
 * @param settings - The HeroSettings object to update.
 * @param token - The JWT access token for authentication.
 * @returns A Promise that resolves to the updated HeroSettings.
 */
export async function updateHeroSettings(settings: HeroSettings, token: string): Promise<HeroSettings> {
  const response = await fetch(`${API_BASE_URL}/api/settings/hero`, {
    method: 'PUT',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${token}`,
    },
    body: JSON.stringify(settings),
  });

  if (!response.ok) {
    const errorData = await response.json();
    throw new Error(errorData.detail || 'Failed to update hero settings');
  }

  return response.json();
}
