"use client";

import { useState, useEffect, useCallback, useMemo } from 'react';
import SimpleMdeReact from "react-simplemde-editor";
import "easymde/dist/easymde.min.css";

// Interface for Blog Post Item - derived from backend model
interface BlogPostItem {
    id?: string;
    title: string;
    subtitle?: string;
    content?: string;
    cover_image?: string;
    tags: string[];
    is_published: boolean;
    published_at?: string; // Using string for simplicity in form, convert to Date when sending
    created_at?: string;
    updated_at?: string;
}

interface BlogFormProps {
  itemToEdit?: BlogPostItem | null;
  onSave: (item: BlogPostItem) => void;
  onCancel: () => void;
}

export default function BlogForm({ itemToEdit, onSave, onCancel }: BlogFormProps) {
  const [item, setItem] = useState<BlogPostItem>({
    title: '',
    subtitle: '',
    content: '',
    cover_image: '',
    tags: [],
    is_published: false,
  });
  const [tagsInput, setTagsInput] = useState('');

  useEffect(() => {
    if (itemToEdit) {
      setItem({
        ...itemToEdit,
        // Ensure published_at is a string if it exists for the form, then convert on save
        published_at: itemToEdit.published_at ? new Date(itemToEdit.published_at).toISOString().split('T')[0] : ''
      });
      setTagsInput(itemToEdit.tags.join(', '));
    } else {
      // Reset form for creation
      setItem({
        title: '',
        subtitle: '',
        content: '',
        cover_image: '',
        tags: [],
        is_published: false,
      });
      setTagsInput('');
    }
  }, [itemToEdit]);

  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => {
    const { name, value } = e.target;
    setItem(prev => ({ ...prev, [name]: value }));
  };

  const handleCheckboxChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const { name, checked } = e.target;
    setItem(prev => ({ ...prev, [name]: checked }));
  };

  const handleMdeChange = useCallback((value: string) => {
    setItem(prev => ({ ...prev, content: value }));
  }, []);

  const handleTagsChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setTagsInput(e.target.value);
    setItem(prev => ({ ...prev, tags: e.target.value.split(',').map(tag => tag.trim()).filter(tag => tag) }));
  }

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    const dataToSend = { ...item };
    // Explicitly remove id, as it's handled by URL param for updates and generated by backend for creates
    if (dataToSend.id) {
        delete dataToSend.id;
    }
    // Adjust published_at for backend if needed
    if (dataToSend.is_published && dataToSend.published_at) {
        // Convert YYYY-MM-DD to ISO string if it's not already
        dataToSend.published_at = new Date(dataToSend.published_at).toISOString();
    } else if (dataToSend.is_published && !dataToSend.published_at) {
        // If published but no date set, set to now
        dataToSend.published_at = new Date().toISOString();
    } else {
        dataToSend.published_at = undefined; // Ensure not sent if unpublished
    }

    onSave(dataToSend);
  };

  const mdeOptions = useMemo(() => {
    return {
      autofocus: false,
      spellChecker: false,
      toolbar: ["bold", "italic", "heading", "|", "quote", "unordered-list", "ordered-list", "|", "link", "image", "|", "guide"],
      placeholder: "Write your blog post content here...",
    };
  }, []);

  return (
    <form onSubmit={handleSubmit} className="space-y-4 text-white">
      <div>
        <label htmlFor="title" className="block text-sm font-medium text-gray-400">Title</label>
        <input
          type="text"
          name="title"
          id="title"
          value={item.title}
          onChange={handleChange}
          required
          className="mt-1 block w-full px-3 py-2 bg-gray-700 border border-gray-600 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500"
        />
      </div>
      <div>
        <label htmlFor="subtitle" className="block text-sm font-medium text-gray-400">Subtitle</label>
        <input
          type="text"
          name="subtitle"
          id="subtitle"
          value={item.subtitle || ''}
          onChange={handleChange}
          className="mt-1 block w-full px-3 py-2 bg-gray-700 border border-gray-600 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500"
        />
      </div>
      <div>
        <label htmlFor="content" className="block text-sm font-medium text-gray-400">Content (Markdown)</label>
         <SimpleMdeReact
            value={item.content || ''}
            onChange={handleMdeChange}
            options={mdeOptions}
            className="mt-1 block w-full"
        />
      </div>
      <div>
        <label htmlFor="cover_image" className="block text-sm font-medium text-gray-400">Cover Image URL</label>
        <input
          type="url"
          name="cover_image"
          id="cover_image"
          value={item.cover_image || ''}
          onChange={handleChange}
          className="mt-1 block w-full px-3 py-2 bg-gray-700 border border-gray-600 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500"
        />
      </div>
      <div>
        <label htmlFor="tags" className="block text-sm font-medium text-gray-400">Tags (comma-separated)</label>
        <input
          type="text"
          name="tags"
          id="tags"
          value={tagsInput}
          onChange={handleTagsChange}
          className="mt-1 block w-full px-3 py-2 bg-gray-700 border border-gray-600 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500"
        />
      </div>
      <div className="flex items-center space-x-2">
        <input
          type="checkbox"
          name="is_published"
          id="is_published"
          checked={item.is_published}
          onChange={handleCheckboxChange}
          className="form-checkbox h-4 w-4 text-indigo-600 transition duration-150 ease-in-out"
        />
        <label htmlFor="is_published" className="text-sm font-medium text-gray-400">Published</label>
      </div>
      {item.is_published && (
        <div>
          <label htmlFor="published_at" className="block text-sm font-medium text-gray-400">Published At</label>
          <input
            type="date"
            name="published_at"
            id="published_at"
            value={item.published_at || ''}
            onChange={handleChange}
            className="mt-1 block w-full px-3 py-2 bg-gray-700 border border-gray-600 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500"
          />
        </div>
      )}
      <div className="flex justify-end space-x-4 pt-4">
        <button
          type="button"
          onClick={onCancel}
          className="px-4 py-2 text-sm font-medium text-gray-300 bg-gray-600 rounded-md hover:bg-gray-500"
        >
          Cancel
        </button>
        <button
          type="submit"
          className="px-4 py-2 text-sm font-medium text-white bg-indigo-600 rounded-md hover:bg-indigo-700"
        >
          Save
        </button>
      </div>
    </form>
  );
}